name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fake-bank-repo/fake-bank-app:latest .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fake-bank-repo/fake-bank-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fake-bank-app \
            --image=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fake-bank-repo/fake-bank-app:latest \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated \
            --memory=512Mi \
            --port=3001 \
            --set-env-vars=PORT=3001,SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL }},REDIS_URL=${{ secrets.REDIS_URL }},MAIL_HOST=${{ secrets.MAIL_HOST }},MAIL_PORT=${{ secrets.MAIL_PORT }},MAIL_USER=${{ secrets.MAIL_USER }},MAIL_PASS=${{ secrets.MAIL_PASS }}
